# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b6b6dc9ca736f16a811d2817b75d241dedc6df70f81bc2141ff5d9037257f9816f26a5344f942ed49d12dcdd7ef573cedeb5f97e26430f06af08becac54f94b8

test:
  secret_key_base: c74cb2d9af4a21ba5b0f7c46d338ff99831372c5a2670e1941bcb766cc393f724ab5569c0d441f628756c3f5408f5eea02a32ae481e0413c384b5d16188d92e4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
